### ISSUE TITLE
Remove testing constants from app.js

### ISSUE THREAD

**Issue by kieferm** [jrsconfitto/VisVirtualHackathon#14]
Remove the following debug variables.  If they are needed can they be coded into `local-dev.html`?

```
var _WebAPIServer = "https://dan-af-dev/piwebapi";
var afServer = "dan-af-dev"
var afDatabase = "Mineral Processing";
var databaseRootURLComplete;
var elementPath = '\\\\DAN-AF-DEV\\Mineral Processing\\Toll Ore Delivery\\T-101'
```

**Comment by kieferm** [comment]
Is there any way reference the contents of `sym-treemap-template.html` and `treemap.css` into `local-dev.html`?

The reason is that as we make changes to the template html it might be good to see it reflected in the local-dev.

This is a low priority, the files can be manually updated.

**Comment by FishmanD** [comment]
Yes, we should be able to add them as references into local-dev.html.  See how local-dev.html references the scripts.

**Comment by jrsconfitto** [comment]
One problem with including the template into the `local-dev`:

1. If we use angular templating (e.g. replacing `id="whatever"` with `id={{elementId}}`) in the template file, the local-dev stuff will not follow suit unless we add some other templating solution locally.

That's not a huge problem, we can add some quick & dirty templating in there. HTML templating libraries are a dime a dozen.

**Comment by jrsconfitto** [comment]
i think we're done here, reopen if not.
