### ISSUE TITLE
display total duration

### ISSUE THREAD

**Issue by FishmanD** [jrsconfitto/VisVirtualHackathon#41]
Display the total duration of all EF in a title box.  We are doing BI, and it might be interesting to see total runtime/downtime as user switches context/time range.

**Comment by jrsconfitto** [comment]
See https://github.com/jrsconfitto/VisVirtualHackathon/issues/43#issuecomment-283150424 for more information on where to look for changing that.

**Comment by jrsconfitto** [comment]
...unless you want to adjust the text in the cell instead of the "title" element, not sure. You'd want to change around the area of the following line of code: https://github.com/jrsconfitto/VisVirtualHackathon/blob/7f3b26b5593c322d2b09f982cddceb5f189fe291/app.js#L115

**Comment by jrsconfitto** [comment]
(not expecting this before you're back in town, btw)

**Comment by kieferm** [comment]
Implemented in #51
