### ISSUE TITLE
Add Template Name to Hover Tool Tip

### ISSUE THREAD

**Issue by kieferm** [jrsconfitto/VisVirtualHackathon#43]

**Comment by jrsconfitto** [comment]
You're in luck! This is an easy one to adjust!

You'll want to change the `text` value of the cell's `"title"` element. This can be found in the [app.js file's `treemap` function](https://github.com/jrsconfitto/VisVirtualHackathon/blob/7f3b26b5593c322d2b09f982cddceb5f189fe291/app.js#L119).

So far, there isn't a ton of properties on the `d.data` object worth showing there, but you have access to any property in the `myEventFrame` object under the `d.data.ef` property.

Let me know if you need any help 😄

**Comment by jrsconfitto** [comment]
(not expecting this before you're back in town, btw)
